-- packages/admin/d1/schema.sql
CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, title TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 0, due TEXT);
CREATE TABLE IF NOT EXISTS failures (id TEXT PRIMARY KEY, text TEXT NOT NULL, retryable INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'failed');
CREATE TABLE IF NOT EXISTS changes (id TEXT PRIMARY KEY, text TEXT NOT NULL, recent INTEGER NOT NULL DEFAULT 1, ts INTEGER);
CREATE TABLE IF NOT EXISTS metrics (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS releases (id TEXT PRIMARY KEY, title TEXT NOT NULL, release_time TEXT);
CREATE TABLE IF NOT EXISTS logs (id TEXT PRIMARY KEY, text TEXT NOT NULL, ts INTEGER);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT UNIQUE, role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, actor TEXT, action TEXT, target TEXT, ts INTEGER);
